
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DopaChat.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Assistant
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string ProfilePicture { get; set; }

    public string Website { get; set; }

    public string Telephone { get; set; }

    public int CityId { get; set; }

    public string CityName { get; set; }



    public virtual City City { get; set; }

}

}
